"""Deterministic rainfall-series fixture generator.

Produces a 7-day synthetic 5-minute rainfall series exercising every rolling
window from 5 min to 168 h. No randomness — output is byte-stable across
runs and machines.

Usage:
    python tests/golden/fixtures/build_rainfall_series.py

Writes:
    tests/golden/fixtures/rainfall_series_synthetic_7d.json
"""
import json
import os
from datetime import datetime, timedelta, timezone

OUT = os.path.join(
    os.path.dirname(__file__),
    'rainfall_series_synthetic_7d.json',
)

START = datetime(2025, 1, 6, 0, 0, 0, tzinfo=timezone.utc)  # Mon 2025-01-06 00:00 UTC
INTERVAL_MIN = 5
DURATION_DAYS = 7
TICKS_PER_DAY = (24 * 60) // INTERVAL_MIN  # 288
TOTAL_TICKS = DURATION_DAYS * TICKS_PER_DAY  # 2016

# Per-tick rainfall mm (0-indexed). Each tick covers 5 minutes.
# Designed so each rolling window has a clearly identifiable peak.
def value_for_tick(t):
    day = t // TICKS_PER_DAY  # 0..6
    tick_of_day = t % TICKS_PER_DAY  # 0..287

    if day == 0:
        # Mon: light morning shower 06:00-07:00 (12 ticks). Total ~3 mm.
        if 72 <= tick_of_day < 84:
            return 0.25
        return 0.0

    if day == 1:
        # Tue: moderate steady rain 09:00-15:00 (72 ticks). 0.2 mm/tick = 14.4 mm total.
        if 108 <= tick_of_day < 180:
            return 0.2
        return 0.0

    if day == 2:
        # Wed: dry
        return 0.0

    if day == 3:
        # Thu: SEVERE thunderstorm 14:00-15:00 (12 ticks).
        # Peak structure: 6 ticks ramping to 8 mm, then 6 ticks ramping down.
        # 5-min max should be 8 mm. 30-min max should be ~30 mm. 1-h max should be ~40 mm.
        burst_start = 168  # tick 168 = 14:00
        if burst_start <= tick_of_day < burst_start + 6:
            # Ramp up: 1, 3, 5, 7, 8, 8
            return [1.0, 3.0, 5.0, 7.0, 8.0, 8.0][tick_of_day - burst_start]
        if burst_start + 6 <= tick_of_day < burst_start + 12:
            # Ramp down: 7, 5, 3, 2, 1, 0.5
            return [7.0, 5.0, 3.0, 2.0, 1.0, 0.5][tick_of_day - burst_start - 6]
        # Tail: light rain rest of afternoon
        if burst_start + 12 <= tick_of_day < burst_start + 36:
            return 0.15
        return 0.0

    if day == 4:
        # Fri: sustained moderate rain 06:00-12:00 (72 ticks). 0.7 mm/tick = 50.4 mm total.
        # Should dominate the 6-h window.
        if 72 <= tick_of_day < 144:
            return 0.7
        # Light tail in afternoon
        if 144 <= tick_of_day < 192:
            return 0.05
        return 0.0

    if day == 5:
        # Sat: dry
        return 0.0

    if day == 6:
        # Sun: light intermittent showers, total ~5 mm spread across 6 short bursts.
        # Three 4-tick bursts at 0.4 mm/tick = 4.8 mm total.
        for burst_start in (60, 156, 240):  # 05:00, 13:00, 20:00
            if burst_start <= tick_of_day < burst_start + 4:
                return 0.4
        return 0.0

    return 0.0


def build_series():
    series = []
    for t in range(TOTAL_TICKS):
        ts = START + timedelta(minutes=t * INTERVAL_MIN)
        v = value_for_tick(t)
        # Round to 2 dp so the fixture is exactly representable
        v = round(v, 2)
        series.append({
            'timestamp': ts.strftime('%Y-%m-%dT%H:%M:%SZ'),
            'value': v,
        })
    return series


def main():
    series = build_series()
    payload = {
        '_description': '7-day synthetic rainfall series at 5-minute resolution. Deterministic. Generated by tests/golden/fixtures/build_rainfall_series.py.',
        'start_iso': START.strftime('%Y-%m-%dT%H:%M:%SZ'),
        'interval_minutes': INTERVAL_MIN,
        'tick_count': len(series),
        'total_depth_mm': round(sum(r['value'] for r in series), 2),
        'series': series,
    }
    # Write with stable formatting — sorted keys would change the schema; use indent=2
    with open(OUT, 'w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2)
        f.write('\n')
    print(f'wrote {len(series)} readings ({payload["total_depth_mm"]} mm total) to {OUT}')


if __name__ == '__main__':
    main()
